version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25

  - package-ecosystem: nuget
    directory: "/tests"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
